import type { SectionType } from "./types";

export interface SectionDefinition {
  type: SectionType;
  label: string;
  icon: string;
  description: string;
  variants: string[];
  defaultVariant: string;
  defaultContent: Record<string, unknown>;
  /** Sections that source data from proposal-level arrays, not section.content */
  dataSource?: "days" | "properties" | "pricing" | "inclusions" | "practicalInfo";
}

export const SECTION_REGISTRY: Record<SectionType, SectionDefinition> = {
  operatorHeader: {
    type: "operatorHeader",
    label: "Operator Header",
    icon: "▣",
    description: "Branded letterhead with logo, company name, and contact details",
    variants: ["minimal", "centered-brand", "split-logo-details", "transparent-overlay"],
    defaultVariant: "minimal",
    defaultContent: {},
  },
  cover: {
    type: "cover",
    label: "Cover",
    icon: "◻",
    description: "Cinematic title page with client name, dates, and hero image",
    variants: ["cinematic-split", "flip-split", "centered-editorial", "minimal-type", "full-bleed-overlay"],
    defaultVariant: "cinematic-split",
    defaultContent: { heroImageUrl: "", tagline: "" },
  },
  greeting: {
    type: "greeting",
    label: "Greeting",
    icon: "✉",
    description: "Personal introduction from the consultant",
    variants: ["editorial-letter", "two-column-consultant", "centered-minimal", "sidebar-accent"],
    defaultVariant: "editorial-letter",
    defaultContent: { body: "Dear Guest,\n\nIt is a genuine pleasure to put this proposal together for you." },
  },
  tripSummary: {
    type: "tripSummary",
    label: "Trip Summary",
    icon: "◈",
    description: "Quick-read stats: destinations, duration, pax, budget",
    variants: ["default", "wide-grid"],
    defaultVariant: "default",
    defaultContent: {},
  },
  itineraryTable: {
    type: "itineraryTable",
    label: "Itinerary at a Glance",
    icon: "☰",
    description: "Auto-generated table from day data",
    variants: ["default", "compact"],
    defaultVariant: "default",
    defaultContent: {},
    dataSource: "days",
  },
  dayJourney: {
    type: "dayJourney",
    label: "Day-by-Day Journey",
    icon: "✦",
    description: "Rich day cards with images, narratives, and camp options",
    variants: ["split-text-image", "flip-split", "stacked-image-text", "compact-timeline", "magazine-spread", "full-image-overlay"],
    defaultVariant: "split-text-image",
    defaultContent: {},
    dataSource: "days",
  },
  propertyShowcase: {
    type: "propertyShowcase",
    label: "Property Showcase",
    icon: "⌂",
    description: "Camp and lodge detail cards",
    variants: ["editorial", "image-left-details-right", "large-image-detail-block", "hero-thumbnails", "card-grid", "full-bleed"],
    defaultVariant: "editorial",
    defaultContent: {},
    dataSource: "properties",
  },
  pricing: {
    type: "pricing",
    label: "Pricing",
    icon: "$",
    description: "Investment overview with 3-tier pricing",
    variants: ["default", "compact", "horizontal", "minimal"],
    defaultVariant: "default",
    defaultContent: {},
    dataSource: "pricing",
  },
  inclusions: {
    type: "inclusions",
    label: "Inclusions & Exclusions",
    icon: "✓",
    description: "What's included and what's not",
    variants: ["default", "split-columns"],
    defaultVariant: "default",
    defaultContent: {},
    dataSource: "inclusions",
  },
  practicalInfo: {
    type: "practicalInfo",
    label: "Practical Information",
    icon: "ℹ",
    description: "Visas, health, packing, and travel tips",
    variants: ["card-grid", "two-column-notes", "icon-list", "accordion-style"],
    defaultVariant: "card-grid",
    defaultContent: {},
    dataSource: "practicalInfo",
  },
  closing: {
    type: "closing",
    label: "Closing",
    icon: "◐",
    description: "Elegant sign-off from the consultant",
    variants: ["quote-led", "letter-style", "centered-minimal", "cta-card"],
    defaultVariant: "quote-led",
    defaultContent: {
      quote: "Africa changes you.",
      signOff: "With warm regards,",
    },
  },
  footer: {
    type: "footer",
    label: "Footer",
    icon: "—",
    description: "Consultant contact details and branding",
    variants: ["default", "minimal"],
    defaultVariant: "default",
    defaultContent: {},
  },
  customText: {
    type: "customText",
    label: "Custom Text",
    icon: "T",
    description: "Free-form text block",
    variants: ["default", "centered", "full-width"],
    defaultVariant: "default",
    defaultContent: { heading: "", body: "" },
  },
  quote: {
    type: "quote",
    label: "Pull Quote",
    icon: "❝",
    description: "Large pull quote with attribution",
    variants: ["default", "centered"],
    defaultVariant: "centered",
    defaultContent: { quote: "", attribution: "" },
  },
  gallery: {
    type: "gallery",
    label: "Gallery",
    icon: "⊞",
    description: "Image grid layout",
    variants: ["2-column", "3-column", "4-column"],
    defaultVariant: "3-column",
    defaultContent: { images: [] },
  },
  divider: {
    type: "divider",
    label: "Divider",
    icon: "─",
    description: "Horizontal rule",
    variants: ["line", "ornamental", "spacious"],
    defaultVariant: "line",
    defaultContent: {},
  },
  spacer: {
    type: "spacer",
    label: "Spacer",
    icon: "↕",
    description: "Vertical whitespace",
    variants: ["sm", "md", "lg", "xl"],
    defaultVariant: "md",
    defaultContent: {},
  },
  map: {
    type: "map",
    label: "Map",
    icon: "◎",
    description: "Route map placeholder",
    variants: ["default", "full-width"],
    defaultVariant: "default",
    defaultContent: { embedUrl: "", caption: "Kenya Safari Route" },
  },
};

export const ADDABLE_SECTIONS: SectionType[] = [
  "operatorHeader",
  "cover",
  "greeting",
  "tripSummary",
  "itineraryTable",
  "dayJourney",
  "propertyShowcase",
  "pricing",
  "inclusions",
  "practicalInfo",
  "closing",
  "footer",
  "customText",
  "quote",
  "gallery",
  "divider",
  "spacer",
  "map",
];
