// Starter library — famous East African camps + lodges new operators can
// load with one click. The prose is grounded in publicly-known facts
// about each property; operators are expected to edit / replace / archive.
//
// Covers the classic northern Tanzania circuit, the Kenyan north (Mara /
// Samburu / Lewa), city stopovers, lake properties, and a post-safari
// beach finale. Enough to build any typical East African demo proposal
// without having to create a single property manually.

// Image URLs intentionally REMOVED from the starter library.
//
// Operator brief: seeded properties were arriving with hardcoded
// Unsplash stock photos, and when operators deleted those photos
// (uploading their own), the same generic shots resurrected through
// various code paths (template builds reading from STARTER_LIBRARY,
// proposal regeneration paths). Cleaner to ship the starter library
// imageless — operators must upload from day one, no ghost photos
// can ever come back.
//
// `leadImageUrl` and `galleryUrls` stay on the type as empty strings
// / empty arrays for back-compat with existing callers (buildProposal,
// seed-starter) — those callers handle empty URLs gracefully.

export type StarterProperty = {
  name: string;
  propertyClass: string;
  locationName: string;
  country: string;
  region?: string;
  shortSummary: string;
  whatMakesSpecial: string;
  whyWeChoose: string;
  amenities: string[];
  mealPlan: string;
  suggestedNights: number;
  suitability: string[];
  tags: string[];
  // Showcase fields
  leadImageUrl: string;
  galleryUrls: string[];
  checkInTime: string;
  checkOutTime: string;
  totalRooms: number;
  spokenLanguages: string[];
  specialInterests: string[];
};

export const STARTER_LIBRARY: StarterProperty[] = [
  // ── Kenya — Maasai Mara ────────────────────────────────────────────────
  {
    name: "Angama Mara",
    propertyClass: "lodge",
    locationName: "Maasai Mara",
    country: "Kenya",
    region: "Oloololo Escarpment",
    shortSummary: "Thirty tents on the edge of the Oloololo Escarpment, with a 1,000-foot view over the Mara Triangle.",
    whatMakesSpecial: "The view is the property. Every tent faces the same drop to the Mara plains. Beadwork studio on site, photographic workshop programme, and a resident photographer who rides with guests when asked.",
    whyWeChoose: "For first-time Mara guests who want a long horizon and a sense of scale. Not the choice if your clients want deep bush immersion — Angama is a grand hotel on a cliff, not a camp.",
    amenities: ["Infinity pool", "Spa", "Wi-Fi", "Photographic studio", "Beadwork studio", "Private dining", "Sundowner deck", "Guided walks"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["honeymoon", "first_time", "photography"],
    tags: ["luxury", "view"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:30",
    totalRooms: 30,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Big Five", "Great Migration", "Photography", "Cultural"],
  },
  {
    name: "Cottar's 1920s Safari Camp",
    propertyClass: "tented_camp",
    locationName: "Maasai Mara",
    country: "Kenya",
    region: "Olderkesi Conservancy",
    shortSummary: "Ten canvas tents styled in 1920s colonial detail, set on a private conservancy bordering the Mara and the Serengeti.",
    whatMakesSpecial: "Cottar's family has been guiding safaris in East Africa since 1919. The conservancy means night drives, walking safaris, and four guests per vehicle — plus access to both the Mara and Serengeti when seasonal movements justify it.",
    whyWeChoose: "The classic-style camp for guests who care about heritage and guiding craft over contemporary design. Families take the bush villa; photographers stay longer than planned.",
    amenities: ["Pool", "Spa", "Library", "Private dining", "Guided walks", "Night drives", "Sundowner deck", "Kids' programme"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["families", "experienced", "photography", "small_groups"],
    tags: ["luxury", "conservancy", "heritage"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "13:30",
    checkOutTime: "10:30",
    totalRooms: 10,
    spokenLanguages: ["English", "Swahili", "French"],
    specialInterests: ["Big Five", "Walking safaris", "Night drives", "Cultural"],
  },

  // ── Kenya — Nairobi stopover ────────────────────────────────────────────
  {
    name: "Giraffe Manor",
    propertyClass: "boutique_hotel",
    locationName: "Nairobi",
    country: "Kenya",
    shortSummary: "Twelve rooms in a 1930s manor house on a suburban Nairobi reserve, home to a resident herd of Rothschild giraffes.",
    whatMakesSpecial: "The giraffes come to breakfast. They put their heads through the dining-room windows for a pellet. That is the visit — the giraffes are the brief.",
    whyWeChoose: "One-night stopover between flights, especially for families and first-time guests. Book six months out at minimum; the hotel is almost always sold out.",
    amenities: ["Wi-Fi", "Lounge", "Library", "Gardens", "Breakfast with giraffes", "Kids' programme"],
    mealPlan: "full_board",
    suggestedNights: 1,
    suitability: ["families", "first_time", "honeymoon", "kids_under_12"],
    tags: ["iconic", "city"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 12,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Giraffe encounter", "Conservation", "Cultural", "Family"],
  },

  // ── Tanzania — Grumeti / Serengeti ──────────────────────────────────────
  {
    name: "Singita Grumeti — Sasakwa Lodge",
    propertyClass: "lodge",
    locationName: "Grumeti",
    country: "Tanzania",
    region: "Western Serengeti",
    shortSummary: "Ten Edwardian-style cottages on a hilltop above the Grumeti reserve, with private plunge pools and a polo pitch below.",
    whatMakesSpecial: "The 340,000-acre Grumeti Reserves is private. The wildebeest migration comes through May–July and again in November. Staff-to-guest ratio is high even by Singita standards.",
    whyWeChoose: "Repeat Africa guests who've done the classic Serengeti circuit and want a private-concession experience at the highest end. Not for first-timers — the price point doesn't make sense without frame of reference.",
    amenities: ["Private plunge pool", "Spa", "Wine cellar", "Library", "Gym", "Tennis", "Equestrian centre", "Private dining"],
    mealPlan: "all_inclusive",
    suggestedNights: 4,
    suitability: ["honeymoon", "experienced", "small_groups"],
    tags: ["luxury", "private-concession"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 10,
    spokenLanguages: ["English", "Swahili", "French", "Italian"],
    specialInterests: ["Great Migration", "Big Five", "Photography", "Private concession"],
  },
  {
    name: "Serengeti Under Canvas",
    propertyClass: "mobile_camp",
    locationName: "Serengeti",
    country: "Tanzania",
    shortSummary: "Nine tents that follow the wildebeest migration through the year, pitched in different Serengeti locations each season.",
    whatMakesSpecial: "Mobile camp in the real sense — the whole property moves four times a year to stay within an hour of the migration. Bucket showers, solar lanterns, lion calls at night.",
    whyWeChoose: "When clients ask for 'the migration' and mean it. Not a first-trip choice unless the operator prepares them — it's a working camp, not a resort.",
    amenities: ["Safari tents", "Bucket shower", "Private dining", "Guided walks", "Night drives", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["experienced", "photography", "honeymoon"],
    tags: ["migration", "mobile"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "13:00",
    checkOutTime: "10:00",
    totalRooms: 9,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Great Migration", "Big Five", "River crossings", "Photography"],
  },

  // ── Tanzania — Ngorongoro ───────────────────────────────────────────────
  {
    name: "The Highlands, Ngorongoro",
    propertyClass: "lodge",
    locationName: "Ngorongoro",
    country: "Tanzania",
    region: "Olmoti volcano rim",
    shortSummary: "Eight dome-shaped suites on the Olmoti volcano rim, thirty minutes above the Ngorongoro Crater.",
    whatMakesSpecial: "The domes are warm — a real point when you're at 2,600 metres. Ngorongoro Crater descent is daily; on rest days, guided walks up Olmoti with Maasai trackers.",
    whyWeChoose: "A fresh take on the Ngorongoro base camp for guests who find the crater-rim lodges too formal. Pair with a Serengeti mobile camp for the full classic northern Tanzania loop.",
    amenities: ["Wood stove", "Spa", "Wi-Fi", "Guided walks", "Library", "Private dining", "Kids' programme"],
    mealPlan: "full_board",
    suggestedNights: 2,
    suitability: ["families", "first_time", "experienced"],
    tags: ["highlands", "crater"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    totalRooms: 8,
    spokenLanguages: ["English", "Swahili", "Maasai"],
    specialInterests: ["Ngorongoro Crater", "Cultural (Maasai)", "Walking safaris", "Big Five"],
  },

  // ── Tanzania — Tarangire ────────────────────────────────────────────────
  {
    name: "Chem Chem Lodge",
    propertyClass: "lodge",
    locationName: "Tarangire",
    country: "Tanzania",
    region: "Chem Chem Concession",
    shortSummary: "Eight canvas suites in a 16,000-acre private corridor between Tarangire and Lake Manyara.",
    whatMakesSpecial: "The private concession means walking, biking, and night drives — none of which you can do inside Tarangire National Park. Elephants through camp most afternoons in dry season.",
    whyWeChoose: "Right for guests who want elephants, low density, and the flexibility of a private concession without leaving the northern circuit.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Guided walks", "Bikes", "Night drives", "Library", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["honeymoon", "photography", "small_groups"],
    tags: ["concession", "elephants"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "13:30",
    checkOutTime: "10:30",
    totalRooms: 8,
    spokenLanguages: ["English", "Swahili", "French", "Italian"],
    specialInterests: ["Elephants", "Walking safaris", "Bike safaris", "Private concession"],
  },

  // ── Kenya — Laikipia / Lewa ─────────────────────────────────────────────
  {
    name: "Sirikoi",
    propertyClass: "lodge",
    locationName: "Lewa Wildlife Conservancy",
    country: "Kenya",
    region: "Laikipia",
    shortSummary: "Six tents, two cottages, and a family house on the Lewa Wildlife Conservancy, a UNESCO site with a 25-year rhino conservation record.",
    whatMakesSpecial: "Sirikoi is the Roberts family's home with guests in it. Rhino tracking on foot, camel rides, and helicopter picnics are all on the activity menu. Every dollar supports Lewa.",
    whyWeChoose: "For guests who want a property that feels personal and conservation-led. Perfect for a Laikipia leg before heading to the Mara.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Horse riding", "Camel trekking", "Rhino tracking", "Guided walks", "Private dining"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["families", "experienced", "photography", "small_groups"],
    tags: ["conservancy", "rhino"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:30",
    totalRooms: 9,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Rhino tracking", "Conservation", "Horse riding", "Helicopter safaris"],
  },

  // ── Kenya — Samburu ─────────────────────────────────────────────────────
  {
    name: "Saruni Samburu",
    propertyClass: "lodge",
    locationName: "Samburu",
    country: "Kenya",
    region: "Kalama Conservancy",
    shortSummary: "Six open-fronted villas on a kopje above the Kalama Conservancy, a community-owned reserve neighbouring Samburu National Reserve.",
    whatMakesSpecial: "Samburu guiding — reticulated giraffe, Grevy's zebra, Beisa oryx, the northern Kenya 'special five' that don't live further south. Cultural time with Samburu warriors is part of most itineraries here.",
    whyWeChoose: "When the brief is 'not the Mara' and the guest has the flexibility for a third country-ish leg. Low guest numbers, high variety.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Guided walks", "Cultural visits", "Night drives", "Library", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["honeymoon", "experienced", "photography"],
    tags: ["conservancy", "cultural"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:30",
    totalRooms: 6,
    spokenLanguages: ["English", "Swahili", "Samburu"],
    specialInterests: ["Samburu Special Five", "Cultural", "Walking safaris", "Photography"],
  },

  // ── Tanzania — Zanzibar beach ────────────────────────────────────────────
  {
    name: "Mnemba Island Lodge",
    propertyClass: "boutique_hotel",
    locationName: "Zanzibar",
    country: "Tanzania",
    region: "Mnemba Atoll",
    shortSummary: "Twelve bandas on a private island off the north-east coast of Zanzibar, rebuilt by &Beyond with a new conservation brief.",
    whatMakesSpecial: "The whole atoll is a marine reserve. Snorkelling from the beach. Sea turtles nest on the island. Resident conservation team runs regular releases that guests join.",
    whyWeChoose: "The post-safari finale. Perfect for a three-to-four night decompression after a northern circuit or Mara trip.",
    amenities: ["Beach", "Snorkelling", "Diving", "Spa", "Private dining", "Library", "Kids' programme", "Marine conservation activities"],
    mealPlan: "all_inclusive",
    suggestedNights: 4,
    suitability: ["honeymoon", "families", "first_time"],
    tags: ["beach", "island", "conservation"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 12,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Beach", "Snorkelling", "Diving", "Marine conservation"],
  },

  // ═══ NEW — 10 additions covering missing locations ═══════════════════════

  // ── Tanzania — Arusha (gateway) ─────────────────────────────────────────
  {
    name: "Mount Meru Game Lodge",
    propertyClass: "lodge",
    locationName: "Arusha",
    country: "Tanzania",
    region: "Usa River",
    shortSummary: "A historic lodge on a 35-acre wildlife sanctuary fifteen minutes from Arusha airport, with orphaned animals in open enclosures and Mount Meru above.",
    whatMakesSpecial: "The sanctuary hosts cheetahs, zebras, antelope, and waterbirds in the wetlands. Classic stone-and-thatch rooms that feel rooted in a different era of East African travel.",
    whyWeChoose: "A straightforward first-night stop for clients landing at Kilimanjaro Airport and starting the northern circuit the next morning. Low fuss, reliable, close to the safari route.",
    amenities: ["Pool", "Wi-Fi", "Restaurant", "Gardens", "Wildlife sanctuary", "Airport transfers", "Bar", "Lounge"],
    mealPlan: "half_board",
    suggestedNights: 1,
    suitability: ["first_time", "families", "short_stay"],
    tags: ["gateway", "airport"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    totalRooms: 15,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Wildlife sanctuary", "Gateway stopover", "Gardens"],
  },
  {
    name: "Arusha Coffee Lodge",
    propertyClass: "lodge",
    locationName: "Arusha",
    country: "Tanzania",
    region: "Burka Coffee Estate",
    shortSummary: "Thirty plantation suites set on a 300-acre working coffee estate on the outskirts of Arusha, with coffee tours and plantation walks.",
    whatMakesSpecial: "The estate is still a commercial coffee farm. Rooms are individual suites among the trees; the main lodge is a converted planter's house. Coffee from the estate is served at breakfast.",
    whyWeChoose: "Best stopover option for guests who want something with character on the first or last night — more personal than the airport hotels, still efficient for departures.",
    amenities: ["Pool", "Wi-Fi", "Coffee tour", "Spa", "Restaurant", "Gardens", "Airport transfers", "Library"],
    mealPlan: "half_board",
    suggestedNights: 1,
    suitability: ["honeymoon", "first_time", "short_stay"],
    tags: ["gateway", "coffee"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 30,
    spokenLanguages: ["English", "Swahili", "German"],
    specialInterests: ["Coffee tour", "Gateway stopover", "Plantation walks", "Cultural"],
  },

  // ── Kenya — Amboseli ────────────────────────────────────────────────────
  {
    name: "Tortilis Camp",
    propertyClass: "tented_camp",
    locationName: "Amboseli",
    country: "Kenya",
    region: "Amboseli private conservancy",
    shortSummary: "Sixteen tents under thorn trees on a private conservancy bordering Amboseli National Park, with Kilimanjaro filling the skyline.",
    whatMakesSpecial: "Kilimanjaro views are the brief — tents are oriented to catch the dawn light on the mountain. The private conservancy adds walking safaris and night drives that you can't do inside the park.",
    whyWeChoose: "The photographer's Amboseli. Pair with a Mara stay for a classic Kenya 'elephants + cats' loop.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Guided walks", "Night drives", "Private dining", "Library", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 2,
    suitability: ["honeymoon", "photography", "first_time"],
    tags: ["elephants", "kilimanjaro"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "13:30",
    checkOutTime: "10:30",
    totalRooms: 16,
    spokenLanguages: ["English", "Swahili", "French"],
    specialInterests: ["Elephants", "Kilimanjaro views", "Photography", "Walking safaris"],
  },
  {
    name: "Ol Tukai Lodge",
    propertyClass: "lodge",
    locationName: "Amboseli",
    country: "Kenya",
    shortSummary: "Eighty rooms at the heart of Amboseli National Park, on the site of the original Ernest Hemingway tented camp.",
    whatMakesSpecial: "Inside-the-park location on Observation Hill — elephants walk past the swimming pool most afternoons in dry season. Big, reliable lodge operation rather than an intimate camp.",
    whyWeChoose: "The value pick for Amboseli. Family rooms, adjoining rooms, big-group logistics all work here. Not for guests chasing intimacy, but great for first-timers and multigenerational trips.",
    amenities: ["Pool", "Wi-Fi", "Restaurant", "Gardens", "Family rooms", "Gift shop", "Kids' programme", "Guided drives"],
    mealPlan: "full_board",
    suggestedNights: 2,
    suitability: ["families", "first_time", "kids_under_12"],
    tags: ["value", "elephants"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    totalRooms: 80,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Elephants", "Kilimanjaro views", "Family", "Value"],
  },

  // ── Tanzania — Lake Manyara ─────────────────────────────────────────────
  {
    name: "Lake Manyara Serena Safari Lodge",
    propertyClass: "lodge",
    locationName: "Lake Manyara",
    country: "Tanzania",
    region: "Rift Valley escarpment",
    shortSummary: "Sixty-seven rondavel-style rooms high on the Rift Valley escarpment, overlooking Lake Manyara and the plains beyond.",
    whatMakesSpecial: "The escarpment-top location gives you the lake, the forested slopes, and the alkaline flats in one sweep. Safe, full-service lodge operation on a dramatic site.",
    whyWeChoose: "Reliable mid-range stop on the northern Tanzania circuit, especially between Tarangire and Serengeti. Not glamorous, but gets the Manyara day done efficiently.",
    amenities: ["Pool", "Wi-Fi", "Restaurant", "Gardens", "Viewing deck", "Family rooms", "Guided drives", "Gift shop"],
    mealPlan: "full_board",
    suggestedNights: 1,
    suitability: ["families", "first_time", "short_stay"],
    tags: ["rift-valley", "value"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    totalRooms: 67,
    spokenLanguages: ["English", "Swahili", "German"],
    specialInterests: ["Rift Valley views", "Tree-climbing lions", "Birdlife", "Forest walks"],
  },
  {
    name: "&Beyond Lake Manyara Tree Lodge",
    propertyClass: "tree_lodge",
    locationName: "Lake Manyara",
    country: "Tanzania",
    region: "Lake Manyara National Park",
    shortSummary: "Ten stilted treehouse suites inside Lake Manyara National Park, the only permanent property inside the park boundary.",
    whatMakesSpecial: "Inside-the-park exclusivity means you're first at the lake gate each morning and last to leave at sunset. Suites are built around mahogany trees; the shower is open to the canopy.",
    whyWeChoose: "When the operator brief is 'Manyara done properly, not as a drive-through'. Pair with a Serengeti or Grumeti leg for a tight luxury northern circuit.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Private dining", "Guided walks", "Sundowner deck", "Library", "Kids' programme"],
    mealPlan: "all_inclusive",
    suggestedNights: 2,
    suitability: ["honeymoon", "experienced", "photography"],
    tags: ["luxury", "treehouse"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 10,
    spokenLanguages: ["English", "Swahili", "French"],
    specialInterests: ["Treehouse suites", "Tree-climbing lions", "Birdlife", "Forest walks"],
  },

  // ── Kenya — Lake Nakuru ─────────────────────────────────────────────────
  {
    name: "Sarova Lion Hill Game Lodge",
    propertyClass: "lodge",
    locationName: "Lake Nakuru",
    country: "Kenya",
    region: "Lake Nakuru National Park",
    shortSummary: "Sixty-seven chalet-style rooms on a wooded hillside inside Lake Nakuru National Park, overlooking the alkaline lake.",
    whatMakesSpecial: "Lake Nakuru is the rhino sanctuary park — both black and white rhinos, plus the flamingo flocks when water levels cooperate. The lodge sits above the treeline on a dedicated hill with long-view sundowners.",
    whyWeChoose: "Classic choice for a Kenya Rift Valley loop. Pair with Lake Naivasha for a two-night interlude between Nairobi and the Mara.",
    amenities: ["Pool", "Wi-Fi", "Restaurant", "Gardens", "Viewing deck", "Gift shop", "Guided drives", "Bar"],
    mealPlan: "full_board",
    suggestedNights: 1,
    suitability: ["families", "first_time", "short_stay"],
    tags: ["rhino", "rift-valley"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    totalRooms: 67,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Rhino", "Flamingos", "Birdlife", "Rift Valley views"],
  },

  // ── Kenya — Lake Naivasha ───────────────────────────────────────────────
  {
    name: "Loldia House",
    propertyClass: "boutique_hotel",
    locationName: "Lake Naivasha",
    country: "Kenya",
    region: "Lake Naivasha",
    shortSummary: "Eight rooms in a lakeside farmhouse on a working 6,500-acre cattle and wildlife ranch, with private access to Lake Naivasha.",
    whatMakesSpecial: "Loldia is a family home on the ranch the Nightingale family has farmed since the 1960s. Walking, boating, horseback rides — wildlife moves across the property freely. Very un-lodgey, very personal.",
    whyWeChoose: "For guests who want one night that feels like staying with friends on a historic farm. Sits well between Nairobi and the Mara, especially for multi-generational trips.",
    amenities: ["Pool", "Wi-Fi", "Boating", "Horse riding", "Guided walks", "Private dining", "Library", "Gardens"],
    mealPlan: "full_board",
    suggestedNights: 2,
    suitability: ["families", "honeymoon", "small_groups"],
    tags: ["heritage", "ranch"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 8,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Boat safaris", "Horse riding", "Birdlife", "Walking safaris"],
  },
  {
    name: "Chui Lodge",
    propertyClass: "lodge",
    locationName: "Lake Naivasha",
    country: "Kenya",
    region: "Oserian Wildlife Sanctuary",
    shortSummary: "Eight thatched cottages on the 18,000-acre Oserian Wildlife Sanctuary above Lake Naivasha, surrounded by leopards, giraffes and grazing herds.",
    whatMakesSpecial: "Chui means leopard in Swahili and the sanctuary lives up to it — leopards routinely pass through camp at night. Walking and night drives are both permitted on the sanctuary.",
    whyWeChoose: "A quieter alternative to Loldia when guests want a bush-camp feel on Naivasha rather than a farmhouse. Good photography base.",
    amenities: ["Pool", "Spa", "Wi-Fi", "Guided walks", "Night drives", "Private dining", "Library", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 2,
    suitability: ["honeymoon", "experienced", "photography"],
    tags: ["conservancy", "leopards"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:30",
    totalRooms: 8,
    spokenLanguages: ["English", "Swahili"],
    specialInterests: ["Leopards", "Walking safaris", "Night drives", "Photography"],
  },

  // ── Kenya — Meru ────────────────────────────────────────────────────────
  {
    name: "Elsa's Kopje",
    propertyClass: "lodge",
    locationName: "Meru",
    country: "Kenya",
    region: "Meru National Park",
    shortSummary: "Ten open-fronted cottages built into a rocky kopje overlooking the plains of Meru National Park, named for Elsa the lioness of Born Free.",
    whatMakesSpecial: "The kopje setting — cottages are literally part of the rock, open to the view on three sides. Meru itself is quiet, wild, and restored: rhino sanctuary, big elephant herds, no crowds.",
    whyWeChoose: "For repeat Kenya clients who've done Mara and Samburu and want somewhere fresh. Very private, very photogenic. Pair with Lewa for a Laikipia-to-Meru loop.",
    amenities: ["Infinity pool", "Spa", "Wi-Fi", "Guided walks", "Cultural visits", "Private dining", "Library", "Sundowner deck"],
    mealPlan: "full_board",
    suggestedNights: 3,
    suitability: ["honeymoon", "experienced", "photography"],
    tags: ["kopje", "remote"],
    leadImageUrl: "",
    galleryUrls: [],
    checkInTime: "14:00",
    checkOutTime: "10:30",
    totalRooms: 10,
    spokenLanguages: ["English", "Swahili", "Italian"],
    specialInterests: ["Born Free heritage", "Rhino sanctuary", "Walking safaris", "Photography"],
  },
];
