import type { LayoutManifest } from "../types";

// ─── Pricing layout manifest ───────────────────────────────────────────────
//
// Standard pricing card:
//
//   Section title (h2)                    y:20
//   Section intro                         y:38
//   ┌────────────────────────────────────┐
//   │ pricing table bg (cream / dark)    │ y:55–105
//   │   row_1: label · calc · total      │ y:65
//   │   row_2: label · calc · total      │ y:80
//   │   GRAND TOTAL (right-aligned, h3)  │ y:100
//   └────────────────────────────────────┘
//   Included list ─────│ Excluded list   │ y:120–200
//   Payment block  ────│ Cancellation    │ y:205–255
//   Footer notes (full width)              y:260–290

export const PRICING_STANDARD: LayoutManifest = {
  id: "pricing-standard",
  section: "pricing",
  page_count: 1,
  description:
    "Editorial pricing card with table + included/excluded columns + payment + cancellation",
  slots: [
    {
      type: "text",
      name: "section_title",
      content_key: "sectionTitle",
      x_mm: 18, y_mm: 20, w_mm: 174, h_mm: 16,
      style: "h2",
      color_role: "headingText",
      max_chars: 60,
    },
    {
      type: "text",
      name: "section_intro",
      content_key: "sectionIntro",
      x_mm: 18, y_mm: 38, w_mm: 174, h_mm: 12,
      style: "caption",
      color_role: "mutedText",
      max_chars: 140,
    },
    {
      type: "fill",
      name: "pricing_table_bg",
      x_mm: 18, y_mm: 55, w_mm: 174, h_mm: 50,
      fill: "sectionBg",
    },
    {
      type: "text",
      name: "row_1_label",
      content_key: "row1Label",
      x_mm: 25, y_mm: 65, w_mm: 80, h_mm: 10,
      style: "body",
      color_role: "bodyText",
      max_chars: 40,
    },
    {
      type: "text",
      name: "row_1_calc",
      content_key: "row1Calc",
      x_mm: 110, y_mm: 65, w_mm: 40, h_mm: 10,
      style: "body",
      color_role: "mutedText",
      alignment: "right",
    },
    {
      type: "text",
      name: "row_1_total",
      content_key: "row1Total",
      x_mm: 150, y_mm: 65, w_mm: 35, h_mm: 10,
      style: "body",
      color_role: "headingText",
      alignment: "right",
    },
    {
      type: "text",
      name: "row_2_label",
      content_key: "row2Label",
      x_mm: 25, y_mm: 80, w_mm: 80, h_mm: 10,
      style: "body",
      color_role: "bodyText",
    },
    {
      type: "text",
      name: "row_2_calc",
      content_key: "row2Calc",
      x_mm: 110, y_mm: 80, w_mm: 40, h_mm: 10,
      style: "body",
      color_role: "mutedText",
      alignment: "right",
    },
    {
      type: "text",
      name: "row_2_total",
      content_key: "row2Total",
      x_mm: 150, y_mm: 80, w_mm: 35, h_mm: 10,
      style: "body",
      color_role: "headingText",
      alignment: "right",
    },
    {
      type: "text",
      name: "grand_total",
      content_key: "grandTotal",
      x_mm: 25, y_mm: 100, w_mm: 160, h_mm: 12,
      style: "h3",
      color_role: "headingText",
      alignment: "right",
    },
    // ─── Included / Not included — header label + bulleted list ────
    {
      type: "text",
      name: "included_label",
      x_mm: 18, y_mm: 122, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 9,
      letter_spacing_em: 0.18,
      uppercase: true,
      max_chars: 24,
    },
    {
      type: "text",
      name: "included_list",
      content_key: "includedList",
      x_mm: 18, y_mm: 130, w_mm: 80, h_mm: 70,
      style: "caption",
      color_role: "bodyText",
      size_pt: 10,
      line_height: 1.45,
      max_chars: 600,
      overflow_behavior: "truncate",
    },
    {
      type: "text",
      name: "excluded_label",
      x_mm: 110, y_mm: 122, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 9,
      letter_spacing_em: 0.18,
      uppercase: true,
      max_chars: 24,
    },
    {
      type: "text",
      name: "excluded_list",
      content_key: "excludedList",
      x_mm: 110, y_mm: 130, w_mm: 80, h_mm: 70,
      style: "caption",
      color_role: "bodyText",
      size_pt: 10,
      line_height: 1.45,
      max_chars: 600,
      overflow_behavior: "truncate",
    },

    // Hairline separator between lists and policy blocks.
    {
      type: "fill",
      name: "policy_separator",
      x_mm: 18, y_mm: 208, w_mm: 174, h_mm: 0.3,
      fill: "border",
      opacity: 0.5,
    },

    // ─── Payment / Cancellation policy blocks ────────────────────────
    {
      type: "text",
      name: "payment_block",
      content_key: "paymentBlock",
      x_mm: 18, y_mm: 214, w_mm: 80, h_mm: 50,
      style: "caption",
      color_role: "bodyText",
      size_pt: 9,
      line_height: 1.4,
      max_chars: 320,
    },
    {
      type: "text",
      name: "cancellation_block",
      content_key: "cancellationBlock",
      x_mm: 110, y_mm: 214, w_mm: 80, h_mm: 50,
      style: "caption",
      color_role: "bodyText",
      size_pt: 9,
      line_height: 1.4,
      max_chars: 320,
    },
    {
      type: "text",
      name: "footer_blocks",
      content_key: "footerBlocks",
      x_mm: 18, y_mm: 268, w_mm: 174, h_mm: 22,
      style: "caption",
      color_role: "mutedText",
      size_pt: 9,
      line_height: 1.4,
      alignment: "center",
      max_chars: 300,
    },
  ],
  rules: [
    "Table rows must not exceed allocated height",
    "All numeric columns right-aligned",
    "Included and excluded lists must not exceed 80mm height",
    "No auto column stacking",
    "Bottom blocks fixed to y_mm 205–297",
    "Overflow truncates with warning",
  ],
};

// ─── Magazine clone — "editorial" pricing variant ────────────────────────
//
// Mirrors the magazine PricingSection layout on a single A4 page:
//   y:14   "YOUR INVESTMENT" eyebrow
//   y:22   "Breakdown of Costs" h2 / 28pt
//   y:46   Value-framing italic line
//   y:62   Breakdown card (174×46mm, cardBg + border):
//            Adults row     y:68 — label · calc · subtotal
//            Hairline       y:80
//            Child row*     y:84 — label · calc · subtotal (when present)
//            Hairline       y:96
//            Total row      y:100 — TOTAL IN <CCY> · grand total
//   y:114  Pricing notes italic
//   y:122  INCLUDED list  |  NOT INCLUDED list  (80mm cols)
//   y:178  Hairline divider
//   y:184  4 quadrant policy grid (2×2):
//            Payment Schedule | Cancellation Policy
//            Travel Insurance | Terms & Conditions
//   y:288  Brand line

export const PRICING_EDITORIAL: LayoutManifest = {
  id: "editorial",
  section: "pricing",
  page_count: 1,
  description: "Magazine-clone pricing — Your Investment / Breakdown / Lists / Policies",
  slots: [
    {
      type: "fill",
      name: "section_bg",
      x_mm: 0, y_mm: 0, w_mm: 210, h_mm: 297,
      fill: "sectionSurface",
      z_index: 0,
    },

    // ─── Header ──────────────────────────────────────────────────────
    {
      type: "text",
      name: "section_eyebrow",
      x_mm: 18, y_mm: 14, w_mm: 174, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 30,
    },
    {
      type: "text",
      name: "section_title",
      content_key: "sectionTitle",
      x_mm: 18, y_mm: 22, w_mm: 174, h_mm: 16,
      style: "h1",
      color_role: "headingText",
      size_pt: 28,
      line_height: 1.05,
      font_weight: 700,
      letter_spacing_em: -0.01,
      max_chars: 60,
      overflow_behavior: "scale_down",
    },
    {
      type: "text",
      name: "value_framing",
      content_key: "valueFraming",
      x_mm: 18, y_mm: 44, w_mm: 174, h_mm: 12,
      style: "body",
      color_role: "mutedText",
      size_pt: 11,
      line_height: 1.5,
      max_chars: 200,
      overflow_behavior: "truncate",
    },

    // ─── Breakdown card ──────────────────────────────────────────────
    {
      type: "fill",
      name: "breakdown_card_bg",
      x_mm: 18, y_mm: 60, w_mm: 174, h_mm: 50,
      fill: "cardBg",
    },
    // Adults row — label · calc · subtotal
    {
      type: "text",
      name: "adults_label",
      content_key: "adultsLabel",
      x_mm: 26, y_mm: 68, w_mm: 70, h_mm: 7,
      style: "body",
      color_role: "headingText",
      size_pt: 11,
      font_weight: 600,
      line_height: 1.2,
      max_chars: 30,
    },
    {
      type: "text",
      name: "adults_calc",
      content_key: "adultsCalc",
      x_mm: 96, y_mm: 68, w_mm: 50, h_mm: 7,
      style: "caption",
      color_role: "mutedText",
      size_pt: 10,
      line_height: 1.2,
      alignment: "right",
      max_chars: 30,
    },
    {
      type: "text",
      name: "adults_subtotal",
      content_key: "adultsSubtotal",
      x_mm: 148, y_mm: 68, w_mm: 36, h_mm: 7,
      style: "body",
      color_role: "headingText",
      size_pt: 11,
      font_weight: 600,
      line_height: 1.2,
      alignment: "right",
      max_chars: 20,
    },
    {
      type: "fill",
      name: "row_divider_1",
      x_mm: 26, y_mm: 80, w_mm: 158, h_mm: 0.3,
      fill: "border",
      opacity: 0.4,
    },
    // Child row — same layout, hidden when childCount = 0 by leaving
    // content empty.
    {
      type: "text",
      name: "child_label",
      content_key: "childLabel",
      x_mm: 26, y_mm: 84, w_mm: 70, h_mm: 7,
      style: "body",
      color_role: "headingText",
      size_pt: 11,
      font_weight: 600,
      line_height: 1.2,
      max_chars: 30,
    },
    {
      type: "text",
      name: "child_calc",
      content_key: "childCalc",
      x_mm: 96, y_mm: 84, w_mm: 50, h_mm: 7,
      style: "caption",
      color_role: "mutedText",
      size_pt: 10,
      line_height: 1.2,
      alignment: "right",
      max_chars: 30,
    },
    {
      type: "text",
      name: "child_subtotal",
      content_key: "childSubtotal",
      x_mm: 148, y_mm: 84, w_mm: 36, h_mm: 7,
      style: "body",
      color_role: "headingText",
      size_pt: 11,
      font_weight: 600,
      line_height: 1.2,
      alignment: "right",
      max_chars: 20,
    },
    {
      type: "fill",
      name: "row_divider_2",
      x_mm: 26, y_mm: 96, w_mm: 158, h_mm: 0.3,
      fill: "border",
      opacity: 0.7,
    },
    // Total row — TOTAL IN <CCY> · grand total
    {
      type: "text",
      name: "total_label",
      content_key: "totalLabel",
      x_mm: 96, y_mm: 100, w_mm: 50, h_mm: 7,
      style: "eyebrow",
      color_role: "headingText",
      size_pt: 9.5,
      letter_spacing_em: 0.18,
      uppercase: true,
      font_weight: 600,
      line_height: 1.2,
      alignment: "right",
      max_chars: 20,
    },
    {
      type: "text",
      name: "total_amount",
      content_key: "totalAmount",
      x_mm: 148, y_mm: 100, w_mm: 36, h_mm: 7,
      style: "h3",
      color_role: "headingText",
      size_pt: 13,
      font_weight: 700,
      line_height: 1.1,
      alignment: "right",
      max_chars: 20,
    },

    // ─── Pricing notes italic ────────────────────────────────────────
    {
      type: "text",
      name: "pricing_notes",
      content_key: "pricingNotes",
      x_mm: 18, y_mm: 114, w_mm: 174, h_mm: 6,
      style: "caption",
      color_role: "mutedText",
      size_pt: 10,
      line_height: 1.4,
      max_chars: 200,
      overflow_behavior: "truncate",
    },

    // ─── Included / Not included lists ───────────────────────────────
    {
      type: "text",
      name: "included_label",
      x_mm: 18, y_mm: 124, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 24,
    },
    {
      type: "text",
      name: "included_list",
      content_key: "includedList",
      x_mm: 18, y_mm: 132, w_mm: 80, h_mm: 44,
      style: "body",
      color_role: "bodyText",
      size_pt: 10,
      line_height: 1.55,
      max_chars: 500,
      overflow_behavior: "truncate",
    },
    {
      type: "text",
      name: "excluded_label",
      x_mm: 110, y_mm: 124, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 24,
    },
    {
      type: "text",
      name: "excluded_list",
      content_key: "excludedList",
      x_mm: 110, y_mm: 132, w_mm: 80, h_mm: 44,
      style: "body",
      color_role: "bodyText",
      size_pt: 10,
      line_height: 1.55,
      max_chars: 500,
      overflow_behavior: "truncate",
    },
    {
      type: "fill",
      name: "policy_separator",
      x_mm: 18, y_mm: 180, w_mm: 174, h_mm: 0.3,
      fill: "border",
      opacity: 0.5,
    },

    // ─── 2x2 policy grid ─────────────────────────────────────────────
    // Top-left: Payment schedule
    {
      type: "text",
      name: "payment_label",
      x_mm: 18, y_mm: 188, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 30,
    },
    {
      type: "text",
      name: "payment_schedule",
      content_key: "paymentSchedule",
      x_mm: 18, y_mm: 196, w_mm: 80, h_mm: 38,
      style: "body",
      color_role: "bodyText",
      size_pt: 9.5,
      line_height: 1.5,
      max_chars: 360,
      overflow_behavior: "truncate",
    },
    // Top-right: Cancellation policy
    {
      type: "text",
      name: "cancellation_label",
      x_mm: 110, y_mm: 188, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 30,
    },
    {
      type: "text",
      name: "cancellation_policy",
      content_key: "cancellationPolicy",
      x_mm: 110, y_mm: 196, w_mm: 80, h_mm: 38,
      style: "body",
      color_role: "bodyText",
      size_pt: 9.5,
      line_height: 1.5,
      max_chars: 360,
      overflow_behavior: "truncate",
    },
    // Bottom-left: Travel insurance
    {
      type: "text",
      name: "insurance_label",
      x_mm: 18, y_mm: 240, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 30,
    },
    {
      type: "text",
      name: "travel_insurance",
      content_key: "travelInsurance",
      x_mm: 18, y_mm: 248, w_mm: 80, h_mm: 32,
      style: "body",
      color_role: "bodyText",
      size_pt: 9.5,
      line_height: 1.5,
      max_chars: 320,
      overflow_behavior: "truncate",
    },
    // Bottom-right: Terms & Conditions
    {
      type: "text",
      name: "terms_label",
      x_mm: 110, y_mm: 240, w_mm: 80, h_mm: 5,
      style: "eyebrow",
      color_role: "mutedText",
      size_pt: 10,
      letter_spacing_em: 0.3,
      uppercase: true,
      font_weight: 700,
      max_chars: 30,
    },
    {
      type: "text",
      name: "terms_value",
      content_key: "termsValue",
      x_mm: 110, y_mm: 248, w_mm: 80, h_mm: 16,
      style: "body",
      color_role: "headingText",
      size_pt: 11,
      line_height: 1.4,
      font_weight: 600,
      max_chars: 100,
      overflow_behavior: "truncate",
    },
    {
      type: "text",
      name: "terms_url",
      content_key: "termsUrl",
      x_mm: 110, y_mm: 264, w_mm: 80, h_mm: 5,
      style: "caption",
      color_role: "mutedText",
      size_pt: 9,
      letter_spacing_em: 0.04,
      max_chars: 80,
      overflow_behavior: "truncate",
    },
  ],
  rules: [
    "Section fills full A4 (297mm) — magazine pricing clone",
    "Header + value framing y:14-56",
    "Breakdown card y:60-110 with adults / child / total rows",
    "Lists y:124-176 in two 80mm columns",
    "Policy 2x2 grid y:188-280",
  ],
};

export const PRICING_LAYOUTS = [PRICING_STANDARD, PRICING_EDITORIAL];
