"use client";

import { useEffect, useState } from "react";
import { BookingOpsSection } from "./BookingOpsSection";
import { FEATURES } from "@/lib/featureFlags";

// ReservationSummaryDialog — small modal with a 2–3 line concierge brief
// generated by Safari Studio AI for a single ProposalReservation. The
// consultant scans this before opening the full record so they know
// what to lead the conversation with.

type Props = {
  reservationId: string;
  clientName: string | null;
  onClose: () => void;
};

export function ReservationSummaryDialog({
  reservationId,
  clientName,
  onClose,
}: Props) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [brief, setBrief] = useState<string>("");

  const fetchBrief = async () => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/summarize-reservation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reservationId }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(typeof data.error === "string" ? data.error : `HTTP ${res.status}`);
      }
      setBrief(typeof data.brief === "string" ? data.brief : "");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Couldn't generate the summary.");
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    void fetchBrief();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(brief);
    } catch {
      /* swallow — environment without clipboard API */
    }
  };

  return (
    <div
      className="fixed inset-0 z-[1000] flex items-end md:items-center justify-center p-0 md:p-6"
      style={{ background: "rgba(20,20,20,0.55)" }}
      onClick={onClose}
    >
      <div
        className="w-full md:max-w-[520px] max-h-[92vh] overflow-y-auto rounded-t-2xl md:rounded-2xl shadow-2xl"
        style={{ background: "#F7F3E8", color: "#0a1411" }}
        onClick={(e) => e.stopPropagation()}
      >
        <div
          className="flex items-center justify-between gap-3 px-5 md:px-7 pt-5 pb-3"
          style={{ borderBottom: "1px solid rgba(0,0,0,0.10)" }}
        >
          <div className="min-w-0">
            <div
              className="text-[10.5px] uppercase tracking-[0.28em] font-semibold"
              style={{ color: "rgba(10,20,17,0.55)" }}
            >
              Safari Studio AI · Reservation brief
            </div>
            <h2
              className="font-bold leading-[1.1] mt-0.5 truncate"
              style={{
                color: "#0a1411",
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: "1.25rem",
                letterSpacing: "-0.005em",
              }}
            >
              {clientName ? clientName : "Reservation"}
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-2xl leading-none transition hover:opacity-75 shrink-0"
            style={{ color: "rgba(10,20,17,0.55)" }}
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="px-5 md:px-7 py-5 space-y-4">
          {error && (
            <div
              className="rounded-lg p-3 text-[13px]"
              style={{
                background: "rgba(179,67,52,0.08)",
                color: "#b34334",
                border: "1px solid rgba(179,67,52,0.22)",
              }}
            >
              {error}
            </div>
          )}

          {busy && !brief ? (
            <div className="space-y-2">
              <div className="h-3 rounded animate-pulse" style={{ background: "rgba(0,0,0,0.08)" }} />
              <div className="h-3 rounded animate-pulse" style={{ background: "rgba(0,0,0,0.08)" }} />
              <div className="h-3 w-2/3 rounded animate-pulse" style={{ background: "rgba(0,0,0,0.08)" }} />
            </div>
          ) : (
            <p
              className="text-[14.5px] leading-[1.65]"
              style={{ color: "rgba(10,20,17,0.85)" }}
            >
              {brief}
            </p>
          )}

          <p className="text-[11.5px]" style={{ color: "rgba(10,20,17,0.55)" }}>
            Drafted by Safari Studio AI from this reservation&rsquo;s notes and thread.
          </p>
        </div>

        {/* Booking Operations — per-property availability check
            workflow. Generated on demand from the booked proposal's
            itinerary; fully operator-driven (no auto-send, no
            auto-confirm). Gated by FEATURES.bookingOps — held
            internal until the supplier orchestration cadence has
            been validated with pilot operators. The component, API
            and schema all stay shipped so re-enabling is a single
            env-flip + redeploy. */}
        {FEATURES.bookingOps && (
          <BookingOpsSection reservationId={reservationId} />
        )}

        <div
          className="px-5 md:px-7 pb-5 pt-3 flex items-center justify-between gap-3 flex-wrap"
          style={{ borderTop: "1px solid rgba(0,0,0,0.06)" }}
        >
          <button
            type="button"
            onClick={() => void fetchBrief()}
            disabled={busy}
            className="px-3 h-9 rounded-md text-[12.5px] font-semibold disabled:opacity-50"
            style={{
              background: "transparent",
              color: "#0a1411",
              border: "1px solid rgba(0,0,0,0.16)",
            }}
          >
            {busy ? "Summarising…" : "Regenerate"}
          </button>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              disabled={!brief || busy}
              className="px-3 h-9 rounded-md text-[12.5px] font-semibold disabled:opacity-50"
              style={{
                background: "transparent",
                color: "#0a1411",
                border: "1px solid rgba(0,0,0,0.16)",
              }}
            >
              Copy
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-4 h-9 rounded-md text-[13px] font-semibold active:scale-[0.97]"
              style={{ background: "#1b3a2d", color: "#ffffff" }}
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
